apiVersion: v1
kind: Pod
metadata:
  name: whisper-model-uploader
  namespace: debugging-testcrash-pub
spec:
  containers:
  - name: uploader
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: models
      mountPath: /models
  volumes:
  - name: models
    persistentVolumeClaim:
      claimName: whisper-service-v2-models-pvc
  restartPolicy: Never
