tunnel: s3-tunnel
credentials-file: /home/lexus/.cloudflared/95e4576e-3c92-417e-9ff7-8afdd5be777c.json

tunnel: ollama-tunnel
credentials-file: /home/lexus/.cloudflared/cd97b91d-6493-4962-89f2-a4a9db5a6977.json

ingress:
  - hostname: vyby.debug.org.ua
    service: http://localhost:8081
  - hostname: ollama.debug.org.ua
    service: http://100.65.0.209:11434
  - service: http_status:404
