apiVersion: v1
kind: Pod
metadata:
  name: cloudflared-ssh
  namespace: debugging-ollama
spec:
  containers:
  - name: cloudflared
    image: cloudflare/cloudflared:2026.3.0
    env:
    - name: TUNNEL_TOKEN
      value: "eyJhIjoiZmZhMjc2NTFhNjQ3ZDM3YTcxZmIzYWVhZTk2OWM3NjIiLCJ0IjoiMmZiNDgxMTItMDQ0Mi00NjY2LWFjN2ItMjJjMmRmMjczMjgyIiwicyI6IkF4MnBTbnRJNmpvSHErWjZ1TjhWbkNJTG5hZUt2a0luRlFmR3R2TTBSV1k9In0K"
    - name: TUNNEL_INGRESS_CONFIG
      value: '[{"hostname":"ssh-debug.debug.org.ua","service":"ssh://10.0.0.8:22"},{"hostname":"ollama.debug.org.ua","service":"http://10.0.0.8:11434"},{"service":"http_status:404"}]'
    command: ["cloudflared", "tunnel", "--no-autoupdate", "run"]
