apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: debugging-ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path