apiVersion: v1
kind: Config
current-context: kube-dc/kube-dc.cloud/debugging/echovoice
clusters:
    - name: voice-cluste-cp
      cluster:
        server: https://91.224.11.35:6443
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJS0JaY0g3MHEwTXd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1EUXhNREF4TXpWYUZ3MHpOakExTURFeE1EQTJNelZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNXeEZGUkJPblo2Njc5Mkw4QmFZbzhmVXFOSnVOWjFUZ1BiVUVJR0NKV3c0bWJZQU9xT1BoVGxHUCsKWWZIYkNQb2VDR2NqZi9uczBWWDhrTVF1Y2dpZTBLY2tuWTNXaFJSTmhleE1qaC9kOXJYY2tTSWNUQitqVzlSSgo0RnZsdXdBcEZHZG83ellYRkwvZlp1RGlTclN5UGRSODFtdzI3WDVVNWhmTy83UDhjYUtPUmh1YnRPWUxzNzFsCkQrU2paWkM4SnRiUHAwcEhKSUxsOFRmVEVVVjNqQ0xTc2Vxd2c1anM1MmMrM0cweGRnc3VrTnNnK24yOWtndzQKNWVUR0c0RmhQUFJSYTUrbHZ4cHA5a1NwZjBEMmtReWQyN0w5YURqYXQ5NGloM0xZVHV3Z1FiNEIyQXgxSFdWegpsbWpRTUtyN1BOQ0kwWlRPQ216U3luMC9BZzU5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRSWoybnFlLzhZNjJXSGNPWno5Y3FRYWdHbHZUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1M4NE54bHNTSQpkK0c4M1dGMzVOd2tQM2J2UzJoSWxsN2pWTEF3MlpRTTJpMVZhME9xWXUxSzd5QkdKWWtDT1drMi9sN00xQ2pPCmMxRW1EZzB3QWlKZWswWTVCaENMcWdKY1NBdzk5UWV2bFUrL1ZMR091dFpicUNMVC9YQzVSdXZhbmo1VUU1WE0KQVJOYy9JNnRtL3BBZ0k2Y2UwWnUvZXRrTDVoUi9qV2E4dUxoWVc1LzZIWlEwU2JDSHFCWHMrNVo0Zk5QWTU0UwpRTVVtcE9GRmRjY0Q5TlpGQ2NDVTIwTTAzM3RIWXFjTnN3Y2c1ZUpIRXVXYUlJbkg1WWUyblYrbU5qZjdWOTZKCjh4cnJoa3kwbHIzNzlOOGg1SkdPR0ZrMTk3MXVWVitrSEtEb0hQb28yRktHK1ZzQXppQ1U2cDRxWjROUmREa3EKUFdzcnZYWklOTDJUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    - name: kube-dc-kube-dc.cloud-debugging
      cluster:
        server: https://kube-api.kube-dc.cloud:6443
        insecure-skip-tls-verify: true
contexts:
    - name: kubernetes-admin@voice-cluste-cp
      context:
        cluster: voice-cluste-cp
        user: kubernetes-admin
    - name: kube-dc/kube-dc.cloud/debugging/echovoice
      context:
        cluster: kube-dc-kube-dc.cloud-debugging
        user: kube-dc@kube-dc.cloud/debugging
        namespace: debugging-echovoice
    - name: kube-dc/kube-dc.cloud/debugging/ollama-coding
      context:
        cluster: kube-dc-kube-dc.cloud-debugging
        user: kube-dc@kube-dc.cloud/debugging
        namespace: debugging-ollama-coding
users:
    - name: kubernetes-admin
      user: {}
    - name: kube-dc@kube-dc.cloud/debugging
      user:
        exec:
            apiVersion: client.authentication.k8s.io/v1
            command: kube-dc
            args:
                - credential
                - --server
                - https://kube-api.kube-dc.cloud:6443
            interactiveMode: IfAvailable
