name = "whisper-messenger"
main = "src/index.ts"
compatibility_date = "2026-02-13"
workers_dev = false
preview_urls = false
routes = [
  { pattern = "whisper.debug.org.ua/*", zone_name = "debug.org.ua" },
  { pattern = "whisper.debug.org.ua/tg-ws-api/*", zone_name = "debug.org.ua" }
]

[ai]
binding = "AI"

[[queues.producers]]
binding = "AUDIO_QUEUE"
queue = "audio-jobs"

[[kv_namespaces]]
binding = "STATS"
id = "f4b04260ccfa4f1ea34c4fab2d53ed1d"

[[queues.consumers]]
queue = "audio-jobs"
max_batch_size = 1
max_retries = 5

[vars]
VERIFY_TOKEN = "your_verify_token_here"
META_API_VERSION = "v19.0"
WHATSAPP_PHONE_NUMBER_ID = "956619407541550"
BRIDGE_URL = "https://mtproto.debug.org.ua"
BRIDGE_SECRET = "changeme"
WORKER_URL = "https://whisper.debug.org.ua"
SESSION_SECRET = "ZAEBIS_EBANY_NASOS_JORA_GDE_TY_BYL???"

# SMTP Config
EMAIL_FROM = "bpm@debug.org.ua"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "465"
SMTP_SECURE = "true"

# Ollama Config
OLLAMA_BASE_URL = "http://91.224.11.69:11434"
OLLAMA_MODEL = "qwen3-coder:30b"

# Cloudflare R2/S3 Config
CLOUDFLARE_GLOBAL_TOKEN = "c4991c5dcba69ee555673a0f1af9958dafeeb"
CLOUDFLARE_ZONE_ID = "82ec71f790eca83e8c694b7a35e19d69"
CLOUDFLARE_ACCOUNT_ID = "ffa27651a647d37a71fb3aeae969c762"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[rules]]
type = "Text"
globs = ["**/*.css", "**/*.js"]
fallthrough = true