name = "whisper-messenger"
main = "src/index.ts"
compatibility_date = "2026-02-13"

[ai]
binding = "AI"

[[queues.producers]]
binding = "AUDIO_QUEUE"
queue = "audio-jobs"

[[queues.consumers]]
queue = "audio-jobs"
max_batch_size = 1
max_retries = 5

[vars]
VERIFY_TOKEN = "HKnc7fxYvzASGf7cbHpQOhPYvBpqdjghPCpSTW9d"
META_API_VERSION = "v19.0"
WHATSAPP_PHONE_NUMBER_ID = "956619407541550"
WHATSAPP_TOKEN = "EAANHgZB5ANpMBQhwlOUEeVd7JekBcOI4fJAJY7n9CLyfzifmb8WDMZCMJxOHaItrMwZAVelYmtlTJCNr77w0lBDZAnxk7YqufM98OEtcoNS1hNXfTgHtZBAwo9nUFbESf79xDlJ0GE8jFPZCEov2LxZA66S9WWCij4xe9Exh3ZCrnA1L7QBe0RGyzHODu4wIlu01eQmVDaTCM9KZBixhCVcaSrsVE3yZBtJ3XeTBCQ9wvHMfYgPk7IMeaNZCRsrXg7c4dI2dZBHcvwNnwMfS4xfnPI9OhYuTtaTij0pHZACQ8JOZBm"
