name: "[main-instagram-fca-client] Build and push"

on:
  push:
    branches:
      - main
    paths:
      - '.forgejo/workflows/instagram-fca-client.yaml'
      - 'instagram-fca-client/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: kube
    container:
      image: forge.dev.takatan.cloud/takatan/docker-builder:latest
      credentials:
        username: lexus
        password: ${{ secrets.HAJIME_PASSWD }}
    env:
      DOCKER_HOST: tcp://172.18.0.1:2375
      REPO_URL: https://forge.dev.takatan.cloud
      IMG: forge.dev.takatan.cloud/lexus/voicemsg-net
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build -f instagram-fca-client/Dockerfile -t ${{ env.IMG }}:instagram-fca-client-latest -t ${{ env.IMG }}:instagram-fca-client-${{ forgejo.run_number }} instagram-fca-client

      - name: Log in to Registry and push
        run: |
          echo "${{ secrets.HAJIME_PASSWD }}" | docker login ${{ env.REPO_URL }} -u lexus --password-stdin
          docker push ${{ env.IMG }}:instagram-fca-client-${{ forgejo.run_number }} && docker push ${{ env.IMG }}:instagram-fca-client-latest

      - name: Trigger Kubernetes Rollout
        env:
          DOCKER_FORGE_PACKAGE_TOKEN: ${{ secrets.HAJIME_PASSWD }}
        run: |
          
          
          # Use the checked-in kubeconfig instead of interactive login
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/kubeconfig.yaml
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig.yaml

          # Trigger restart
          kubectl delete pod -l app=instagram-fca-client -n debugging-testcrash-pub
