name: "[main-tg-client-manager] Build and push"

on:
  push:
    branches:
      - main
    paths:
      - '.forgejo/workflows/tg-client-manager.yaml'
      - 'kubernetes/base/tg-client-manager.yaml'
      - 'tg-client-manager/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: kube
    container:
      image: forge.dev.takatan.cloud/takatan/docker-builder:latest
      credentials:
        username: lexus
        password: ${{ secrets.DOCKER_FORGE_PACKAGE_TOKEN }}
    env:
      DOCKER_HOST: tcp://172.18.0.1:2375
      REPO_URL: https://forge.dev.takatan.cloud
      IMG: forge.dev.takatan.cloud/lexus/voicemsg-net
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build -f tg-client-manager/Dockerfile -t ${{ env.IMG }}:tg-client-manager-latest -t ${{ env.IMG }}:tg-client-manager-${{ github.sha }} tg-client-manager

      - name: Log in to Registry and push
        run: |
          echo "${{ secrets.DOCKER_FORGE_PACKAGE_TOKEN }}" | docker login ${{ env.REPO_URL }} -u lexus --password-stdin
          docker push ${{ env.IMG }}:tg-client-manager-${{ github.sha }} && docker push ${{ env.IMG }}:tg-client-manager-latest
        env:
          DOCKER_FORGE_PACKAGE_TOKEN: ${{ secrets.DOCKER_FORGE_PACKAGE_TOKEN }}
      - name: Trigger Kubernetes Rollout
        run: |
          # Use the checked-in kubeconfig instead of interactive login
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ~/.kube/config
          # Trigger restart
          kubectl rollout restart deployment tg-client-manager -n debugging-testcrash-pub
