name: "[main-voicemsg-tester] Build and push"

on:
  push:
    branches:
      - main
    paths:
      - '.forgejo/workflows/voicemsg-tester.yaml'
      - 'kubernetes/base/voicemsg-tester.yaml'
      - 'voicemsg-tester/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: kube
    container:
      image: forge.dev.takatan.cloud/takatan/docker-builder:latest
      credentials:
        username: lexus
        password: ${{ secrets.HAJIME_PASSWD }}
    env:
      DOCKER_HOST: tcp://172.18.0.1:2375
      REPO_URL: https://forge.dev.takatan.cloud
      IMG: forge.dev.takatan.cloud/lexus/voicemsg-net
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build -f voicemsg-tester/Dockerfile -t ${{ env.IMG }}:voicemsg-tester-latest -t ${{ env.IMG }}:voicemsg-tester-${{ forgejo.run_number }} voicemsg-tester

      - name: Log in to Registry and push
        run: |
          echo "${{ secrets.HAJIME_PASSWD }}" | docker login ${{ env.REPO_URL }} -u lexus --password-stdin
          docker push ${{ env.IMG }}:voicemsg-tester-${{ forgejo.run_number }} && docker push ${{ env.IMG }}:voicemsg-tester-latest

      - name: Trigger Kubernetes Rollout
        run: |
          
          
          # Use the checked-in kubeconfig instead of interactive login
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/kubeconfig.yaml
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig.yaml

          # Trigger restart
          kubectl rollout restart deployment voicemsg-tester -n debugging-testcrash-pub
