apiVersion: apps/v1
kind: Deployment
metadata:
  name: sherpa-onnx
  namespace: debugging-echovoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sherpa-onnx
  template:
    metadata:
      labels:
        app: sherpa-onnx
    spec:
      containers:
      - name: whisper
        image: azazellosaraksh/debugging-whisper-onnx:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_DIR
          value: /app/models/whisper-tiny
        - name: NUM_THREADS
          value: "4"
        - name: WHISPER_SECRET
          value: "whisper-sh-secret-2026,H@jimeN@maste!"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: sherpa-onnx
  namespace: debugging-echovoice
spec:
  selector:
    app: sherpa-onnx
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
