import base64
import io
import os
import sys
import tempfile
import subprocess
from typing import Optional

from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel
from starlette.responses import StreamingResponse

import torch

# Disable GPU
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["OMP_NUM_THREADS"] = "4"
torch.set_num_threads(4)

TTS_MODEL_DIR = os.environ.get("TTS_MODEL_DIR", "/models")
os.environ["MODELSCOPE_CACHE"] = TTS_MODEL_DIR
MODEL_NAME = os.environ.get(
    "SAMESAME_MODEL_NAME", "FunAudioLLM/Fun-CosyVoice3-0.5B-2512"
)

print(f"[samesame-cosy] Initializing CosyVoice model: {MODEL_NAME}")
sys.path.append("/app/CosyVoice")
sys.path.append("/app/CosyVoice/third_party/Matcha-TTS")

from cosyvoice.cli.cosyvoice import CosyVoice
from cosyvoice.utils.file_utils import load_wav
import torchaudio

try:
    # CosyVoice API (CPU‑only) does not accept `load_onnx`. Keep only supported flags.
    cosyvoice = CosyVoice(MODEL_NAME, load_jit=True, fp16=True)
except Exception as e:
    print(f"[samesame-cosy] Failed to load CosyVoice: {e}")
    sys.exit(1)

SAMESAME_SECRET = os.environ.get("SAMESAME_SECRET")
app = FastAPI(title="Samesame CosyVoice Service")


class CloneRequest(BaseModel):
    source_audio_base64: str
    source_mime_type: Optional[str] = "audio/ogg"
    text: str
    language: Optional[str] = None
    output_format: Optional[str] = "ogg"


@app.get("/health")
@app.get("/live")
def health():
    return {"status": "ok", "model": MODEL_NAME, "backend": "cosyvoice"}


@app.post("/v1/clone")
def clone_voice(req: CloneRequest, authorization: Optional[str] = Header(None)):
    if SAMESAME_SECRET and authorization != f"Bearer {SAMESAME_SECRET}":
        raise HTTPException(status_code=401, detail="Unauthorized")

    if not req.text:
        raise HTTPException(status_code=400, detail="Missing text")

    try:
        audio_bytes = base64.b64decode(req.source_audio_base64)
    except Exception:
        raise HTTPException(
            status_code=400, detail="Invalid base64 in source_audio_base64"
        )

    # Save source audio to temp file
    fd_in, temp_in = tempfile.mkstemp(suffix=".ogg")
    os.write(fd_in, audio_bytes)
    os.close(fd_in)

    # 1. Load the prompt speech
    prompt_speech_16k = load_wav(temp_in, 16000)

    # 2. Extract prompt text using whisper (required for CosyVoice zero_shot)
    import whisper

    whisper_model = whisper.load_model("base", device="cpu")
    # Actually, zero_shot doesn't require prompt_text strictly, but 300M supports 3s-10s prompt speech.

    # We will use cross_lingual inference for zero_shot cloning (keeps voice, new text)
    # The prompt speech needs to be at least 3 seconds.
    print(
        f"[samesame-cosy] Running cross_lingual synthesis for text len={len(req.text)}"
    )

    try:
        # Cross_lingual uses prompt_speech path, no prompt_text is needed!
        output = cosyvoice.inference_cross_lingual(req.text, temp_in)
        tts_audios = []
        for chunk in output:
            if "tts_speech" in chunk:
                tts_audios.append(chunk["tts_speech"])
        if not tts_audios:
            raise ValueError("No tts_speech was generated by CosyVoice")
        tts_audio = torch.cat(tts_audios, dim=1)
    except Exception as e:
        import traceback

        traceback.print_exc()
        os.remove(temp_in)
        raise HTTPException(status_code=500, detail=f"CosyVoice generation failed: {e}")

    fd_out, temp_out = tempfile.mkstemp(suffix=".wav")
    os.close(fd_out)

    # Save to wav
    torchaudio.save(temp_out, tts_audio, 44100)

    os.remove(temp_in)

    # If requested format is ogg, convert using ffmpeg
    if req.output_format == "ogg":
        fd_ogg, temp_ogg = tempfile.mkstemp(suffix=".ogg")
        os.close(fd_ogg)
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-i",
                temp_out,
                "-c:a",
                "libopus",
                "-b:a",
                "128k",
                temp_ogg,
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        os.remove(temp_out)
        temp_out = temp_ogg
        mime = "audio/ogg"
    else:
        mime = "audio/wav"

    with open(temp_out, "rb") as f:
        out_bytes = f.read()

    os.remove(temp_out)

    return {
        "content_type": mime,
        "audio_base64": base64.b64encode(out_bytes).decode("utf-8"),
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("app:app", host="0.0.0.0", port=8002)
