apiVersion: apps/v1
kind: Deployment
metadata:
  name: funasr
  namespace: debugging-testcrash-pub
  labels:
    app: funasr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funasr
  template:
    metadata:
      labels:
        app: funasr
    spec:
      containers:
      - name: funasr-api
        image: harbor.dev.takatan.cloud/azazellosaraksh/funasr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50001
        env:
        - name: FUNASR_MODEL
          value: "Fun-ASR-MLT-Nano"
        - name: FUNASR_DEVICE
          value: "cpu"
        volumeMounts:
        - name: cache-vol
          mountPath: /root/.cache
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "8Gi"
      volumes:
      - name: cache-vol
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: funasr
  namespace: debugging-testcrash-pub
spec:
  type: ClusterIP
  selector:
    app: funasr
  ports:
  - port: 50001
    targetPort: 50001
    protocol: TCP
    name: http
