apiVersion: v1
kind: Secret
metadata:
  name: huggingface-token
  namespace: debugging-testcrash-pub
type: Opaque
stringData:
  # Вставляется при обновлении через update-hf-secret.sh
  HUGGING_FACE_HUB_TOKEN: "__REPLACE_WITH_VALUE__"
