apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voicemsg-ingress
  namespace: debugging-testcrash-cloud
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "http"
spec:
  ingressClassName: nginx
  rules:
    - host: voicemsg.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-frontend
                port:
                  number: 80
    - host: bridge.voicemsg.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mtproto-bridge-manager
                port:
                  number: 3000
    - host: asr.voicemsg.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qwen3-asr
                port:
                  number: 11434
    - host: grafana.voicemsg.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
