apiVersion: v1
kind: ConfigMap
metadata:
  name: insta-fca-pod-template
data:
  pod-template.json: |
    {
      "apiVersion": "v1",
      "kind": "Pod",
      "metadata": {
        "name": "insta-user",
        "labels": {
          "app": "instagram-fca-client",
          "userId": "PLACEHOLDER"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "instagram-fca-client",
            "image": "lexusazazello/instagram-fca-client:latest",
            "imagePullPolicy": "IfNotPresent",
               "env": [
                 {
                   "name": "FUNASR_URL",
                   "value": "http://funasr:50001"
                 },
                 {
                   "name": "MANAGER_URL",
                   "value": "http://instagram-fca-manager:3005"
                 },
                 {
                   "name": "SECRET",
                   "valueFrom": {
                     "secretKeyRef": {
                       "name": "voicemsg-secrets",
                       "key": "MANAGER_SECRET"
                     }
                   }
                 },
                 {
                   "name": "REDIS_URL",
                   "value": "redis://redis:6379"
                 }
               ],
               "resources": {
                 "requests": {
                   "cpu": "20m",
                   "memory": "128Mi"
                 },
                 "limits": {
                   "cpu": "100m",
                   "memory": "256Mi"
                 }
               }
          }
        ],
        "imagePullSecrets": [
          {
            "name": "forgejo-pull-secret"
          }
        ],
        "restartPolicy": "Never"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-fca-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagram-fca-manager
  template:
    metadata:
      labels:
        app: instagram-fca-manager
    spec:
      serviceAccountName: voicemsg-client-manager
      imagePullSecrets:
        - name: forgejo-pull-secret
      containers:
        - name: manager
          image: forge.dev.takatan.cloud/lexus/voicemsg-net:instagram-fca-manager-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: MODE
              value: "MANAGER"
            - name: PORT
              value: "3005"
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: voicemsg-secrets
                  key: MANAGER_SECRET
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/voicemsg"
