apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend.yaml
  - frontend-network-policy.yaml
  - redis.yaml
  - mongodb.yaml
  - network-policy.yaml
  - tg-client-manager.yaml
  - qwen3-asr.yaml
  - tg-client.yaml
  - tg-bot-test.yaml
  - whisper-turbo.yaml
  - voicemsg-cf.yaml
  - rbac.yaml

images:
  - name: mongo
    newName: harbor.dev.takatan.cloud/devcenter/mongo
    newTag: latest
  - name: redis
    newName: harbor.dev.takatan.cloud/devcenter/redis
    newTag: 7-alpine
  - name: qwenllm/qwen3-asr
    newName: harbor.dev.takatan.cloud/devcenter/qwen3-asr
    newTag: latest

namespace: debugging-testcrash-pub
