apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend.yaml
  - redis.yaml
  - mongodb.yaml
  # - network-policy.yaml
  - mtproto-bridge-manager.yaml
  - qwen3-asr.yaml
  - ingress.yaml
  - ingress-nginx.yaml
  - tg-client.yaml
  # - cert-manager.yaml
  - grafana.yaml
  - prometheus.yaml
  - fip.yaml
  - static.yaml
  - grafana-ingress.yaml
  - rbac.yaml

secretGenerator:
- name: grafana-basic-auth
  files:
    - auth

images:
  - name: mongo
    newName: harbor.dev.takatan.cloud/devcenter/mongo
    newTag: latest
  - name: redis
    newName: harbor.dev.takatan.cloud/devcenter/redis
    newTag: 7-alpine
  - name: prom/prometheus
    newName: harbor.dev.takatan.cloud/devcenter/prometheus
    newTag: latest
  - name: fluent/fluentd
    newName: harbor.dev.takatan.cloud/devcenter/fluentd
    newTag: v1.16
  - name: ollama/ollama
    newName: harbor.dev.takatan.cloud/devcenter/ollama
    newTag: latest
  - name: grafana/grafana
    newName: harbor.dev.takatan.cloud/devcenter/grafana
    newTag: latest
  - name: registry.k8s.io/ingress-nginx/controller
    newName: harbor.dev.takatan.cloud/devcenter/ingress-nginx-controller
    newTag: v1.15.1
  - name: qwenllm/qwen3-asr
    newName: harbor.dev.takatan.cloud/devcenter/qwen3-asr
    newTag: latest
  - name: nginx

    newName: harbor.dev.takatan.cloud/devcenter/nginx
    newTag: alpine

namespace: debugging-testcrash-pub
