apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
   - frontend.yaml
   - frontend-network-policy.yaml
   - redis.yaml
   - mongodb.yaml
   - mongo-express.yaml
   - network-policy.yaml
   - tg-client-manager.yaml
   - tg-client.yaml
   - tg-bot-test.yaml
   - whisper-service.yaml
   - whisper-service-v2.yaml
   - whisper-service-network-policy.yaml
   - samesame.yaml
   - samesame-secret.yaml
   - huggingface-secret.yaml
   - rbac.yaml
   - cert-manager.yaml
   - voicemsg-tester.yaml
   - voicemsg-cf.yaml
   - whatsapp-baileys-manager.yaml
   - facebook-fca-manager.yaml



images:
  - name: mongo
    newName: harbor.dev.takatan.cloud/devcenter/mongo
    newTag: latest
  - name: redis
    newName: harbor.dev.takatan.cloud/devcenter/redis
    newTag: 7-alpine
  - name: mongo-express
    newName: harbor.dev.takatan.cloud/devcenter/mongo-express
    newTag: latest

namespace: debugging-testcrash-pub
