apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mtproto-bridge-network-policy
  namespace: debugging-testcrash-pub
spec:
  podSelector:
    matchLabels:
      app: tg-user-bridge
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: mtproto-bridge-manager
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: qwen3-asr
    ports:
    - protocol: TCP
      port: 8000
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
