apiVersion: v1
kind: ServiceAccount
metadata:
  name: tg-client-manager-sa
  namespace: debugging-testcrash-pub
imagePullSecrets:
- name: forgejo-pull-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voicemsg-client-manager
imagePullSecrets:
- name: forgejo-pull-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "persistentvolumeclaims", "configmaps", "endpoints", "secrets", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tg-client-manager-binding
subjects:
- kind: ServiceAccount
  name: tg-client-manager-sa
- kind: ServiceAccount
  name: voicemsg-client-manager
- kind: ServiceAccount
  name: ingress-nginx
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
