apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtproto-bridge-manager
  namespace: debugging-testcrash-pub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: debugging-testcrash-pub
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mtproto-manager-binding
  namespace: debugging-testcrash-pub
subjects:
- kind: ServiceAccount
  name: mtproto-bridge-manager
  namespace: debugging-testcrash-pub
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
