apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samesame
  name: samesame
  namespace: debugging-testcrash-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samesame
  template:
    metadata:
      labels:
        app: samesame
    spec:
      imagePullSecrets:
        - name: dockerhub-pull-secret
      containers:
        - env:
            - name: TTS_MODEL_DIR
              value: "/models"
            - name: HF_HOME
              value: "/models"
            - name: HUGGINGFACE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: token
                  name: huggingface-token
            - name: MODELSCOPE_CACHE
              value: "/models"
            - name: SAMESAME_SECRET
              valueFrom:
                secretKeyRef:
                  key: SAMESAME_SECRET
                  name: voicemsg-secrets
            - name: SAMESAME_MODEL_NAME
              value: "FunAudioLLM/Fun-CosyVoice3-0.5B-2512"
          image: lexusazazello/voicemsg:samesame-latest
          imagePullPolicy: IfNotPresent
          name: samesame
          ports:
            - containerPort: 8002
          resources:
            requests:
              cpu: "1.5"
              memory: "4Gi"
            limits:
              cpu: "1.5"
              memory: "8Gi"
          volumeMounts:
            - mountPath: "/models"
              name: models
            - mountPath: "/app/app.py"
              subPath: "app.py"
              name: app-py
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: samesame-model-cache
        - name: app-py
          configMap:
            name: samesame-app-py

---
apiVersion: v1
kind: Service
metadata:
  name: samesame
  namespace: debugging-testcrash-pub
spec:
  selector:
    app: samesame
  ports:
    - port: 8002
      targetPort: 8002