apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensevoice
  namespace: debugging-testcrash-pub
  labels:
    app: sensevoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensevoice
  template:
    metadata:
      labels:
        app: sensevoice
    spec:
      containers:
        - name: sensevoice
          image: siyrs/sensevoice-api:latest
          command: ["/bin/sh", "-c"]
          args: ["pip install -U modelscope && python /app/SenseVoice/api.py"]
          env:
            - name: SENSEVOICE_DEVICE
              value: "cpu"
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-token
                  key: HUGGING_FACE_HUB_TOKEN
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-token
                  key: HUGGING_FACE_HUB_TOKEN
          ports:
            - containerPort: 50000
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "6Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: sensevoice
  namespace: debugging-testcrash-pub
  labels:
    app: sensevoice
spec:
  selector:
    app: sensevoice
  ports:
    - name: http
      port: 50000
      targetPort: 50000
  type: ClusterIP
