apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-static
  namespace: debugging-testcrash-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-static
  template:
    metadata:
      labels:
        app: echo-static
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-assets
          mountPath: /usr/share/nginx/html/assets
      initContainers:
      - name: build-assets
        image: azazellosaraksh/whisper-frontend:latest
        command: ['sh', '-c', 'cp -r /app/src/ui/* /mnt/static/']
        volumeMounts:
        - name: static-assets
          mountPath: /mnt/static
      volumes:
      - name: static-assets
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: echo-static
  namespace: debugging-testcrash-pub
spec:
  selector:
    app: echo-static
  ports:
  - port: 80
    targetPort: 80
