apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporaly-media-msg
  namespace: debugging-testcrash-pub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
