apiVersion: v1
kind: ConfigMap
metadata:
  name: tts-switch-config
  namespace: debugging-testcrash-pub
data:
  CURRENT_PROVIDER: "samesame"
  SAMESAME_MODEL: "FunAudioLLM/Fun-CosyVoice3-0.5B-2512"
---