apiVersion: v1
kind: Service
metadata:
  name: voicemsg-cf
  labels:
    app: echo-frontend
  annotations:
    service.nlb.kube-dc.com/expose-route: "http"
    service.nlb.kube-dc.com/route-hostname: "voicemsg.net"
    network.kube-dc.com/external-network-type: "cloud"
spec:
  type: LoadBalancer
  selector:
    app: echo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP

