apiVersion: v1
kind: ConfigMap
metadata:
  name: wa-baileys-pod-template
data:
  pod-template.json: |
    {
      "apiVersion": "v1",
      "kind": "Pod",
      "metadata": {
        "name": "wa-baileys-user",
        "labels": {
          "app": "wa-baileys-client"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "wa-baileys-client",
            "image": "lexusazazello/voicemsg:whatsapp-baileys-client-latest",
            "imagePullPolicy": "Always",
            "env": [
              {
                "name": "REDIS_URL",
                "value": "redis://redis:6379"
              },
              {
                "name": "FUNASR_URL",
                "value": "http://funasr:50001"
              },
              {
                "name": "ASR_SECRET",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "voicemsg-secrets",
                    "key": "ASR_SECRET"
                  }
                }
              }
            ],
            "resources": {
              "requests": {
                "cpu": "100m",
                "memory": "128Mi"
              },
              "limits": {
                "cpu": "500m",
                "memory": "512Mi"
              }
            }
          }
        ],
        "imagePullSecrets": [
          {
          "name": "dockerhub-pull-secret"
          }
        ],
        "restartPolicy": "Never"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-baileys-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-baileys-manager
  template:
    metadata:
      labels:
        app: whatsapp-baileys-manager
    spec:
      serviceAccountName: voicemsg-client-manager
      imagePullSecrets:
        - name: forgejo-pull-secret
      containers:
      - name: manager
        image: lexusazazello/voicemsg:whatsapp-baileys-manager-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: MODE
          value: "MANAGER"
        - name: PORT
          value: "3002"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: voicemsg-secrets
              key: MANAGER_SECRET
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: voicemsg-secrets
              key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-baileys-manager
spec:
  selector:
    app: whatsapp-baileys-manager
  ports:
  - port: 3002
    targetPort: 3002