apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: whisper-service-ingress
  namespace: debugging-testcrash-pub
spec:
  podSelector:
    matchLabels:
      app: whisper-service
  policyTypes:
  - Ingress
  ingress:
  - {}