apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-service-v2-models-pvc
  namespace: debugging-testcrash-pub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi   # ← увеличено до 6 GiB
  storageClassName: local-path
