apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: funasr-model-pvc
  namespace: debugging-testcrash-pub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
