apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voicemsg-ingress
  namespace: debugging-testcrash-pub
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - voicemsg.net
      secretName: voicemsg-tls
  rules:
    - host: voicemsg.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-frontend
                port:
                  number: 80