apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testcrash-ingress
  namespace: debugging-testcrash-cloud
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - testcrash-cloud.voicemsg.net
      secretName: voicemsg-tls
  rules:
    - host: testcrash-cloud.voicemsg.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-frontend
                port:
                  number: 80