apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx
  namespace: debugging-testcrash-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/ingress-nginx/controller:v1.9.4
        args:
        - /nginx-ingress-controller
        - --election-id=ingress-nginx-leader
        - --controller-class=k8s.io/ingress-nginx
        - --ingress-class=nginx
        - --enable-ssl-passthrough
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: debugging-testcrash-cloud
  annotations:
    ovn.kubernetes.io/service_external_ip_from_subnet: ext-cloud
spec:
  type: LoadBalancer
  externalIPs:
  - 91.224.11.104
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx