apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

namespace: debugging-testcrash-pub

patches:
- target:
    kind: Ingress
    name: voicemsg-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: voicemsg.net
