apiVersion: v1
kind: Service
metadata:
  name: voicemsg-lb
  namespace: debugging-testcrash-cloud
  annotations:
    ovn.kubernetes.io/load_balancer_ip: "91.224.11.40"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: echo-frontend