apiVersion: v1
kind: Config
current-context: kube-dc/kube-dc.cloud/debugging/voicemsg
clusters:
    - name: kube-dc-kube-dc.cloud-debugging
      cluster:
        server: https://kube-api.kube-dc.cloud:6443
        insecure-skip-tls-verify: true
contexts:
    - name: kube-dc/kube-dc.cloud/debugging/voicemsg
      context:
        cluster: kube-dc-kube-dc.cloud-debugging
        user: kube-dc@kube-dc.cloud/debugging
        namespace: debugging-trash-cloud
users:
    - name: kube-dc@kube-dc.cloud/debugging
      user:
        exec:
            apiVersion: client.authentication.k8s.io/v1
            command: kube-dc
            args:
                - credential
                - --server
                - https://kube-api.kube-dc.cloud:6443
            interactiveMode: IfAvailable
