apiVersion: apps/v1
kind: Deployment
metadata:
  name: sherpa-onnx
  namespace: debugging-echovoice
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sherpa-onnx
  template:
    metadata:
      labels:
        app: sherpa-onnx
    spec:
      containers:
      - name: sherpa
        image: azazellosaraksh/debugging-whisper-onnx:latest
        ports:
        - containerPort: 8000
        env:
        - name: WHISPER_SECRET
          value: "whisper-sh-secret-2026,H@jimeN@maste!"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: sherpa-onnx
  namespace: debugging-echovoice
spec:
  selector:
    app: sherpa-onnx
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
