apiVersion: apps/v1
kind: Deployment
metadata:
  name: sherpa-onnx
  namespace: debugging-echovoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sherpa-onnx
  template:
    metadata:
      labels:
        app: sherpa-onnx
    spec:
      containers:
      - name: sherpa
        image: azazellosaraksh/debugging-whisper-onnx:latest
        ports:
        - containerPort: 8000
        env:
        - name: WHISPER_SECRET
          value: "whisper-sh-secret-2026"
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - eyJhIjoiZmZhMjc2NTFhNjQ3ZDM3YTcxZmIzYWVhZTk2OWM3NjIiLCJ0IjoiYTIxZmRkMDItMmUxNi00ZWVlLWEwY2YtM2ZlNWZhODM1YmI4IiwicyI6Ik9EWmxaREl6TnprdE4yUmhaQzAwTXpBekxXSXhOemt0WVRjeE4yRmxNemc0WW1WaCJ9
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sherpa-onnx
  namespace: debugging-echovoice
spec:
  selector:
    app: sherpa-onnx
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
