apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: debugging-echovoice
type: Opaque
stringData:
  TUNNEL_TOKEN: "eyJhIjoiZmZhMjc2NTFhNjQ3ZDM3YTcxZmIzYWVhZTk2OWM3NjIiLCJ0IjoiYTIxZmRkMDItMmUxNi00ZWVlLWEwY2YtM2ZlNWZhODM1YmI4IiwicyI6Ik9EWmxaREl6TnprdE4yUmhaQzAwTXpBekxXSXhOemt0WVRjeE4yRmxNemc0WW1WaCJ9"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: debugging-echovoice
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - $(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: TUNNEL_TOKEN
