apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: debugging-echovoice
data:
  config.yaml: |
    tunnel: mtproto
    ingress:
      - hostname: mtproto.debug.org.ua
        service: http://mtproto-bridge-manager:3000
      - service: http://localhost:80