apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: debugging-whispermsg
type: Opaque
stringData:
  TUNNEL_TOKEN: "eyJhIjoiZmZhMjc2NTFhNjQ3ZDM3YTcxZmIzYWVhZTk2OWM3NjIiLCJ0IjoiMzc3ZTRhNDItNDQ3OC00MjNhLTg4NTQtNmM1N2RhMDg0MTNhIiwicyI6Ik56SXhNR1pqWkRVdFpXVTBNeTAwWWpFNUxUZzNaV0l0WWpKaVptVmlNemN5TldNMyJ9"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: debugging-whispermsg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - $(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: TUNNEL_TOKEN
