apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: debugging-testcrash-pub

resources:
  - ../../base/frontend.yaml
  - ../../base/redis.yaml
  - ../../base/mongodb.yaml
  - ../../base/tg-client-manager.yaml
  - ../../base/telegram-bot.yaml
  - ../../base/tg-client.yaml
  - ../../base/whatsapp-baileys-manager.yaml
  - ../../base/voicemsg-cf.yaml
  - ../../base/temporaly-media-msg.yaml
  - ../../base/rbac.yaml
  - ../../base/huggingface-secret.yaml
  - ../../base/network-policy.yaml
  - ../../base/frontend-network-policy.yaml
  - ../../base/cert-manager.yaml

configMapGenerator:
  - name: xtts-download-scripts
    files:
      - download-models.sh=../../base/scripts/xtts-download-models.sh
  - name: funasr-download-scripts
    files:
      - download-models.sh=../../base/scripts/funasr-download-models.sh
  - name: samesame-download-scripts
    files:
      - download-models.sh=../../base/scripts/samesame-download-models.sh

generatorOptions:
  disableNameSuffixHash: true
